-- Create databases
CREATE DATABASE IF NOT EXISTS `database1` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS `database2` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;